// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJQFD3k4vtpvIG4_qXgbfDR8Aqdmltmts',
    appId: '1:649462273150:web:51fc91a77eb7a5592cf42f',
    messagingSenderId: '649462273150',
    projectId: 'toumaidary',
    authDomain: 'toumaidary.firebaseapp.com',
    storageBucket: 'toumaidary.appspot.com',
    measurementId: 'G-9XYH9KH58L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNNJr6yeh-d82igG_F_qZT9I-eyOO5rro',
    appId: '1:649462273150:android:9c12ac712b369ff82cf42f',
    messagingSenderId: '649462273150',
    projectId: 'toumaidary',
    storageBucket: 'toumaidary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgmnJpm0qj4Hx3DhMjHE-4fzdP1z22vfc',
    appId: '1:649462273150:ios:0e8c49e0cf774e822cf42f',
    messagingSenderId: '649462273150',
    projectId: 'toumaidary',
    storageBucket: 'toumaidary.appspot.com',
    iosClientId: '649462273150-lih4u9do2ssp15dbrdnmn63et0230ta0.apps.googleusercontent.com',
    iosBundleId: 'com.example.toumaiDary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgmnJpm0qj4Hx3DhMjHE-4fzdP1z22vfc',
    appId: '1:649462273150:ios:0e8c49e0cf774e822cf42f',
    messagingSenderId: '649462273150',
    projectId: 'toumaidary',
    storageBucket: 'toumaidary.appspot.com',
    iosClientId: '649462273150-lih4u9do2ssp15dbrdnmn63et0230ta0.apps.googleusercontent.com',
    iosBundleId: 'com.example.toumaiDary',
  );
}
